Resources:
  RecipesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:custom.tableName}-backup-restored
      AttributeDefinitions:
        - AttributeName: recipeId
          AttributeType: S
      KeySchema:
        - AttributeName: recipeId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES