Resources:
  RecipesTable:
    Type: AWS::DynamoDB::Table
    # DeletionPolicy: ${self:custom.${self:custom.stage}.deletion_policy}
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: recipeId
          AttributeType: S
      KeySchema:
        - AttributeName: recipeId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES